# Plugin information
name: "Database Relations"
description: "Plugin para el manejo de relaciones entre modelos de base de datos."
version: "2.0"
framework_version: "2.0"
dependencies: "db_base"
notes: ""
# Author information
author: "Paul Marclay"
email: "paul.eduardo.marclay@gmail.com"
site: ""
# Legal information
company: "Dolem Labs"
copyright: "(c) 2012 - Paul Marclay"
license: "GNU GENERAL PUBLIC LICENSE"